### ISSUE TITLE
includeEql throws "Object has no method 'some'"

### ISSUE THREAD

**Issue by theycallmeswift** [tj/should.js#33] opened 2012-01-03 23:12 UTC
Looks like somebody had underscore installed when they wrote this method and forgot to test in isolation. No method `some` exists so this throws an error:

`['blah', 'foo', 'bar'].should.includeEql('bar') // throws!`

This is the culprit:

```
  includeEql: function(obj){
     this.assert(
       this.obj.some(function(item) { return eql(obj, item); })
       , 'expected ' + this.inspect + ' to include an object equal to ' + i(obj)
       , 'expected ' + this.inspect + ' to not include an object equal to ' + i(obj));
     return this;
   },
```

**Comment by tj** [comment] 2012-01-03 23:19
`.some` is an `Array.prototype` method, but we should have an assertion for the method and/or being an array in there

**Comment by tj** [comment] 2012-01-03 23:19
not a huge fan of the name either but hey :D

**Comment by theycallmeswift** [comment] 2012-01-04 00:56
I like the method, just can't use it in its current state. Any easy fixes for this?

**Comment by tj** [comment] 2012-01-04 01:00
well your example there works, also you could just do `['blah', 'foo', 'bar'].should.include('bar')` since primitives will be `===`

**Comment by theycallmeswift** [comment] 2012-01-05 02:40
Ah, sorry that was just me not thinking. This is the real problem with include:

```
['blah', 'foo', 'bar-some-other-stuff'].should.include('bar')  #=> true
```

It's not exact so I was getting false positives

**Comment by tj** [comment] 2012-01-05 02:49
hmm failed as expected for me:

```
  0)  test include() with string:
     AssertionError: expected [ 'blah', 'foo', 'bar-some-other-stuff' ] to include 'bar'
```

**Comment by theycallmeswift** [comment] 2012-01-05 02:55
Hmmm.. thats odd. I will see if I can dig up the original code that way failing for me. Thanks for your help btw.

**Comment by tj** [comment] 2012-01-05 02:57
maybe it's an old version of should.js or something

np

**Comment by tj** [comment] 2012-01-06 16:01
closing until we have more info for a confirmed bug

**Closed as completed by tj** 2012-01-06 16:01 UTC
